### PR TITLE
Update testing

### LINKED ISSUE #55: Rewrite tests
### Describe the problem you'd like to have solved

I propose a change to how tests are written after the discussion here: https://github.com/auth0/express-openid-connect/pull/40#issuecomment-562770297

### Describe the ideal solution

As mentioned, I would use the concept [Avoid Nesting when you're Testing](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing), in addition to avoid writing repetitive configs by gathering them on top of each file (or another centralized place like `mockData.js` or something similar), and create a `setup***()` function for tests in a single test suite (file).

Reducing the number of nested `describe()` blocks would also improve readability, by flattening out the test suite. This would be much easier to achieve with the above mentioned `setup***()` functions.

These are not BREAKING CHANGES 💥, as it only touches on the testing part. Though, it must be done carefully, so everything that is tested already is migrated first, and then maybe try to think about adding more tests.

### Additional context

I have mainly used Jest 🃏 for testing, and after working on the `logout.test.js` tests, I would much prefer to do that here as well. Mocha ☕ felt a bit cumbersome, and the outputs were not always easily readable IN MY OPINION.
- [x] ~~If I get green light at work, I may have a bit more time on my hands to work on this then doing it in my free-time.~~ ✔ Green light

### PR DESCRIPTION
**Pull request by balazsorban44**
### Description

As mentioned earlier (see **References**) I would use the concept [Avoid Nesting when you're Testing](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing), in addition to avoiding writing repetitive configs by gathering them on top of each file or using fixtures and create a setup/init function for tests in a single test suite (file).

Reducing the number of nested `describe()` blocks would also improve readability, by flattening out the test suite.

These are **not** BREAKING CHANGES 💥, as it only touches on the testing part. Though, it must be done carefully, so everything that is tested already is migrated first, and then maybe try to think about adding more tests.

As a starter, I only did testing of `/logout`, as I have worked with it previously (see **References**).

__*If* this is still something the maintainers are interested in, I am happy to start migrating the rest of the tests over.__

*To make the least trouble, I plan to duplicate the tests in the beginning, and only make them runnable by running `npm run test:jest`, so the current tests can work as before. Near the end, it can be discussed further if the tests can be safely swapped with the current ones, and finally deleting the old ones.*

### References

This started in #40, and closes #55

### Testing

To test these changes:
1. get this PR locally
2. run `npm install`
3. run `npm run test:jest`

- [x] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by adamjmcgrath** [comment]
> If this is still something the maintainers are interested in, I am happy to start migrating the rest of the tests over.

This look good thanks. I like the approach taken and I think the test style is an improvement 👍

**Comment by adamjmcgrath** [comment]
Am just sorting out the 1.0.0 release, but once I've done that I'll merge this.

Can you add your jest tests to `npm test`? Then feel free to mark this as 'Ready for review' and I'll approve and merge it

**Comment by balazsorban44** [comment]
Hi, sorry for the delay, I am not sure I have the time to actually work on rewriting the rest of the tests, not at the moment at least. I make this "ready for review" and make it up to you to merge this or not. :) At some point I may come back to help with the rest of the testing, cause I would like to contribute, and it made me feel good that you thought this would be an improvement!

**Comment by adamjmcgrath** [comment]
Hi, thanks for your work on this!

We're going to close it for now - but we plan on updating the tests and we'll use your work as a jumping off point

**Pull request closed without merging**
